### ISSUE TITLE
word does not conform to the script of  سيدنا عثمان، رضى الله عنه

### ISSUE THREAD

**Issue by udotag** [quran/quran.com-frontend#1045]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

[
![img_0809](https://user-images.githubusercontent.com/44333106/47278607-cab5ba80-d5e3-11e8-95a0-c82eab783429.png)
](url)

**Expected / new behavior:**

![ayah-reference](https://user-images.githubusercontent.com/44333106/47278765-e53c6380-d5e4-11e8-9f07-f272afe505c3.png)

**For issue, please provide steps to reproduce it:**

https://quran.com/57/27

**Anything else:**

**Comment by ducaale** [comment]
it does confirm to Uthmani script

![20190509_175248](https://user-images.githubusercontent.com/16341131/57463658-dfa62280-7283-11e9-8e14-d4ffe3b3e17d.jpg)
![20190509_175431](https://user-images.githubusercontent.com/16341131/57463660-dfa62280-7283-11e9-9a7c-279c602893ab.jpg)

**Comment by ahmedre** [comment]
yes, as @ducaale mentioned and showed above, this conforms to the madani script (which is what the site uses by default).

what you showed in your ticket, @udotag is the naskh script. i know @naveed-ahmad is working on adding it in the next version since some of the rendering between the naskh and madani masa7if are slightly different in the tashkeel and what not.

**Comment by atefBB** [comment]
السلام عليكم. هل هناك مانع من الالتزام بالرسم للعثماني؟

**Comment by ahmedre** [comment]
وعليكم السلام
الموقع يلتزم بالخط العثماني. الأخ يريد الإلتزام بخط النسخ الذي يستخدم في الباكستان والهند

**Comment by udotag** [comment]
بارك الله فيكم 

i did not know about this difference

**Comment by atefBB** [comment]
@ahmedre شكرا على التوضيح.
