### ISSUE TITLE
Player "Loading" requires refresh

### ISSUE THREAD

**Issue by Clement-TS** [quran/quran.com-frontend#1046]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Reproduction process:**

1. Go to https://quran.com/
2. Click to one link, example 1 Al-Fatihah.
3. You see the "Loading" message on the bottom left.
4. When you click on the "Play" icon, nothing happens.
5. Hit refresh on your browser (F5 or reloading icon)
6. Now the sound player displays and is working

**Expected behavior:**

1. Go to https://quran.com/Firefox 62.0.3 (64-bit).
2. Click to one link, example 1 Al-Fatihah.
3. The sound player displays and is working

**Anything else:**

Tested with:
- Google Chrome Version 67.0.3396.62 (Official Build) (64-bit)
- Firefox 62.0.3 (64-bit)

I guess this is related to the HTML5 history API, which does not properly trigger the player initialisation. While hitting refresh, or going directly to  https://quran.com/1 does the trick.
https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by zishanAhmad** [comment]
Facing the same issue. Can we please fix this

**Comment by imadmk** [comment]
Regarding Audio Player, I found that in https://staging.quran.com, the problem above doesn't exist. And staging looks like has upgraded Audio Player.

I assume that many of Audio Player issue actually already solved, but why it is not merged in production yet? Is there a problem that prevents that?

**Comment by naveed-ahmad** [comment]
@imadmk yes, checkout beta.quran.com 

We'll deploy this to production soon inshAllah, then close lots of these already fixed issues on github.

**Comment by fsultani** [comment]
As-salāmu ʿalaykum. I'd like to maybe help with this project, but I can't tell which issues are resolved without reading through all the comments.  Can someone update or prioritize the issues?

**Comment by smsjkm** [comment]
Assalamualeikum WR WB,
First of all, JazakAllahum khair, for this application and putting your time and effort for this Noble cause. May Allah SWT grant more rewards to you in this dunya and Akhirah.

The issue I've observed and I am not sure if already others reported that Searcing Aya - "Go To Verse" dropdown.

Testing steps:
1. Open https://quran.com/
2. Select Surah Baqrah
3. in "Go To Verse" dropdown - select 285 aya
then it is navigating to error page - https://quran.com/error/invalid-ayah
Ayah is out of range. Please go to home page and select a Surah/Ayah

But when I search through URL - http://quran.com/2/285 this is working fine

Need to debug this area of code:
              "@type": "SearchAction",
              "target": "https://quran.com/search?q={search_term_string}&referrer=sitelinks_searchbox",
              "query-input": "required name=search_term_string"


Suggestion:  Since "Surah names" drop down working fine, so need to apply same logic to  Go To Verse dropdown as well and also need to check dropdown cascading between these 2 dropdowns
e.g. when selecting surah then all the aya numbers load into Go To Verse dropdown

**Comment by smsjkm** [comment]
Jazak Allahum Khair Brother.
Website looks Alhamdulillah, awesome.
