### ISSUE TITLE
[Feature] Make it Earn some money

### ISSUE THREAD

**Issue by elvirmuslic** [quran/quran.com-frontend#1118]
One more suggestion to the business logic, it should be noted that I have not (yet) seen a way to donate or support the development of the website.
This should be implemented, either as a donation or add extra features that won't be necessary but could be implemented for looks or something similar.

Why? 

People like @naveed-ahmad & @mmahalwy need to be developing more and add cool features, we want this site to be better each year and have more people attracted. This is **NOT** possible without money. 
Basically if we want a good website and a more development faster and better we pay and make some of the core developers lives easier.

- Add feature that will be paid and/or donations
- Use that money to give you a salary or pay for extra hours of development i.e. make site better
- Use the money to pay for better servers and whatnot (QA engineer for instance) 
- Have a public forum so that users can also suggest things and talk about Quran

If you want to you can make a pool on the website to see if users would actually like this.

**Comment by farahalyasari** [comment]
Al Salam Alaikum,

I think you are trying to suggest a fee-for-features model. I do not support that. Recall Ayah 17 to 18 in Surat Al Isra.

English Translation of the meaning of Ayah 17 - 18, Surat Al Isra below:
* Whoever should desire the immediate - We hasten for him from it what We will to whom We intend. Then We have made for him Hell, which he will [enter to] burn, censured and banished (17)
* But whoever desires the Hereafter and exerts the effort due to it while he is a believer - it is those whose effort is ever appreciated [by Allah ] (18)

If you can read Arabic, then  I highly encourage you to read the tafser for these Ayahs at a deeper level here: http://www.elsharawy.com/pdfs/Elsharawy_Kwater_017_015_020.pdf

It would be a big and unfortunate lost for this effort to be rewarded only in the Donya. May Allah accept the hard work of @naveed-ahmad and @mmahalwy and reward them in the akera and in this Donya and increase both of their rizk and put barakah in them. 

Please do not add any money payment features to quran.com. 

Jazakom Allah Khairan.

**Comment by elvirmuslic** [comment]
I'm really trying to contain myself here @farahalyasari from making jokes. 
Nothing can work without money, literally, as I've mentioned even zekat is so that the gov can work and those that collect the zekat are one of the higher category of those that should recieve it.

Now if you're going to push it I will consult a expert on this matter i.e. Islamic fikh & economy expert, but I'd prefer not to. Haj is not free and it is an obligation for every muslim, dont you think Saudia Arabia should be charging for it or would you like a dirty and unclean place of worship. Your local imam, shouldnt he receive a compensation, someone to teach the kids and clean the masjid.

Everyone can to these for free, do you?

**Comment by farahalyasari** [comment]
Al Salam Alaikom Elvir,

Please give me some time or a few days, I will consult with a scholar I know. 

I will ask her about the matter of getting reward in the Akera if this web application adds fee-for-features. 

Best,

**Comment by elvirmuslic** [comment]
That'd awesome, may Allah bless you. I would love to hear what they have to say.

**Comment by naveed-ahmad** [comment]
Asalamu alaikum brothers, going to close this. JazakAllah kharian for your du'as and good wishes. InshAllah quran.com, quranicaudio.com, android and ios apps will be ad free, hopefully donation free as well. Lot of brothers and sisters has contributed their time, content(translations/audio), developing and maintaining these apps/websites for sake of Allah subhanwatalah. 

Let's stop discussing money, and be part of this great platform, make it better inshAllah.
