### ISSUE TITLE
Arabic not showing and Logo 

### ISSUE THREAD

**Issue by abdelouali** [quran/quran.com-frontend#123]
![image](https://cloud.githubusercontent.com/assets/13354388/9981627/704a6b12-5fc2-11e5-8992-77006cbee2bc.png)

Like you see on the screenshot. The logo is gone and the arabic quran text is showing weird.

**Comment by abdelouali** [comment]
I think there is some issues with the cdn (content delivery network)

http://quran-1f14.kxcdn.com/images/logo-md-w.png

**Comment by ATouhou** [comment]
It is caused by the custom font not being loaded... If it is not served by
the CDN,  then that makes sense ( that the bug is due to that). There
should be some fallback to use font hosted on the same server if the CDN
does not serve... Mark this issue as feature suggestion?
Den 20/09/2015 6.11 PM skrev "Abdelouali Benkheil" <notifications@github.com

**Comment by ahmedre** [comment]
jazakAllah khairan, fixed this. the problem is that the cdn is "prepaid," and doesn't have a "charge my card automatically when i am finished with my credits" option. will speak with them and see if there's a way around this, otherwise will likely switch to another cdn.

**Comment by abdelouali** [comment]
JazakAllah kahiran Ahmed. I will close this issue. 

Wassalamoualikoem
