### ISSUE TITLE
"stronger impact" hyperlink on Contribute page is not working

### ISSUE THREAD

**Issue by aam1r** [quran/quran.com-frontend#129]
1) Go to http://quran.com
2) Click **Contribute** on top right
3) Click **stronger impact**

This will throw a "Cannot find page requested."

On a related note, the hyperlink for **stronger impact** points to http://quran.com/true which doesn't seem correct.

**Comment by mmahalwy** [comment]
@aam1r good find! To be honest, I don't even remember what was the intention of this :( 

I will remove it soon inshallah or if you wanna put out a PR to remove the link?

**Comment by aam1r** [comment]
@mmahalwy would love to submit a PR.

Could you help me set up the environment locally? I installed dependencies by doing `npm install` but running the default `gulp` task threw a lot of dependency issues. I tried manually going through and installing ~10 of them but gave up after a while.

Did I miss a step somewhere? If not, could you update `package.json` with all the dependencies needed?

Thanks

**Comment by ahmedre** [comment]
nice to see you here 3amer :)

this worked for me:
1. `npm install`
2. `npm run build` (at the very least, for `NODE_ENV` of `production`, `packages.json` is up to date)
3. `npm install -g pm2`, 
4. edit `server.js` and replace `8080` with `8000` (otherwise, since pm2 starts on `8000` by default, it will try to read js and css from port `8080` and fail to do so).
5. `pm2 start start.js --no-daemon` - now it is started on port 8000.

@mmahalwy i get a lot of warnings with `npm install` (can we fix this?):

`npm WARN package.json Dependency 'imports-loader' exists in both dependencies and devDependencies, using 'imports-loader@^0.6.3' from dependencies` and
`npm WARN peerDependencies The peer dependency file-loader@* included from url-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency`

(many of the same two errors, but with different dependency names, etc).

**Comment by mmahalwy** [comment]
salam guys, sorry i just saw this.

@aam1r you are all good except use `npm run watch` to run the servers. we no longer use gulp.

I will do some cleaning up of the house tonight inshallah

**Comment by aam1r** [comment]
@mmahalwy great

By the way, is there a reason the donate popup says "This campaign is no longer accepting donations". Intentional or is it a bug?

**Comment by mmahalwy** [comment]
@aam1r good question. Tilt Open now no longer supports donations. I created this but haven't added it.

https://donorbox.org/quran

Perhaps you want to take a stab at it?

**Comment by aam1r** [comment]
Yeah sure, will look at it over the next few days iA
