### ISSUE TITLE
Enable page view based on standard quranic script

### ISSUE THREAD

**Issue by reshadn** [quran/quran.com-frontend#180]
I personally enjoy reading from a physical book since the pages are tactile and can be distinguished. It would be great if we could organize the ayat to view by page based on the standard Othmani quranic script.

**Comment by sharabash** [comment]
i thought i did this, did you guys not put it in?

**Comment by mmahalwy** [comment]
@reshadn it exists. hit the book icon and itll give you the reading mode, which is formatted like the book - we _can_ do more to make it pretty though

**Comment by reshadn** [comment]
True there is a reading mode but it's designed as one continuous page vs
page-by-page. For example you can't see the left and right page like in a
book.  Unless I'm missing something.

**Comment by ATouhou** [comment]
the continuous layout is very fine but, there is 2 things that could be improved / fixed /added.
1. There is a bug, where if you hover on the last word , it jumps down to the next line, (rendering you unable to hover the last word and see the meaning)
2. It would be nice to have a view, where it is sorted by "page", so that the words are placed exactly where they are in the medina mushaf

**Comment by mmahalwy** [comment]
ah yes @reshadn that'd be nice. I feel like it's a _nice to have_
