### ISSUE TITLE
European Cookie Policy Law

### ISSUE THREAD

**Issue by abdelouali** [quran/quran.com-frontend#182]
It has since 2013 required on each site to show their users that the website uses cookies. On each page where the visitor comes along must be shown that the website is using cookies. This is mandatory and there may be legal consequences for non-compliance of this law. 

For info: it can be a little header that says; This website uses cookies to improve its services.

And if they then click on the cross they agree with the law.

Example: 
![banner_preview](https://cloud.githubusercontent.com/assets/13354388/11326547/c7ad8372-916c-11e5-844b-92bd0e3014e3.jpg)

**Comment by mmahalwy** [comment]
@ahmedre

**Comment by ATouhou** [comment]
if the site is not hosted in EU, then that legislation does not apply to them??

**Comment by abdelouali** [comment]
I don't think so, because big companies like google and facebook also show to their European visitors that they use cookies.

**Comment by azizur** [comment]
The cookies low also applies to local storage.

**Comment by sabeurthabti** [comment]
Closing this issue. Based on the assumption while our users can be from an EU nation, the servers are not.

**Comment by ATouhou** [comment]
Just wrote 2 major assignments in "EU LAW" about this topic.
To summarize:
The Cookie Law is a directive passed by the European Council.
A Directive means all EU nations must adopt this in their local law, while they can change it to fit their countries needs. 
There are 36 different control instances across EU and only 3 fines were ever given (2 in Spain & 1 in Netherlands).
Cookies for functionality is excluded. 3rd party trackers such as Google Analytics is not.
Facebook was sued by Belgium, but since their main european office is in Ireland, it was overruled. 


Assuming Quran.com is not OWNED by Europeans, serving europeans - which it is not - no further action on this is required. 

Key words here are OWNED by Europeans and not the server locations.  


3 Weeks ago a proposal for a regulation was leaked, which is expected to come somewhat 2017.  
A regulation is binding law across all European countries.
However since this is an "american project" then no need to give this any further attention :P
