### ISSUE TITLE
Need Access to database 

### ISSUE THREAD

**Issue by iOsMechanic** [quran/quran.com-frontend#282]
Hi Mohammed,

Need access to database,please let me know making a quran application.

**Comment by ahmedre** [comment]
the database is not open right now - you can point to our backend using http://api.quran.com:3000

**Comment by iOsMechanic** [comment]
can i get some access to the quran content?

**Comment by dashohoxha** [comment]
An API is much better than a DB dump.
Are there any docs on how to use this API? Or you are just waiting for me to document it?

By the way, I have experience with documenting API-s, see this:
 - http://info.btranslator.org/api/
 - http://info.btranslator.org/api-examples-js/

**Comment by ahmedre** [comment]
i think besides documentation, we still have a few things to think through:
- api keys
- rate limiting
- what apis to expose and what not to expose

in the current world, the api is public, but it's not documented because it's not yet frozen - i imagine that we'll have to distinguish between public and private traffic at some point in the future. at the current moment, we're more or less focusing on site stability and features, and insha'Allah finalizing the public api will come later.

iOsMechanic: most of the stuff we use is from various other sources that are freely available on the internet - example the images are from qurancomplex's fonts and we have a repo for that here (quran/quran.com-images) translations are from tanzil.net (though be careful, some of their translations are not reliable and/or are not sunni), and audio is from a combination of everyayah.com and quranicaudio.com.

**Comment by dashohoxha** [comment]
My opinion is that documentation is not the last thing to be done, even if you have lots of things to think about. It can be as simple as this: https://raw.githubusercontent.com/B-Translator/B-Translator.github.io/master/docs/org/btranslator-api-reference.org
which is a simple org-mode file, easy to write and maintain, especially with Emacs.

GitHub renders it like this: https://github.com/B-Translator/B-Translator.github.io/blob/master/docs/org/btranslator-api-reference.org
which is not so bad.

With Emacs and Jekyll (and some custom CSS, of course), it can be converted automatically to something like this: http://info.btranslator.org/api/

I think it is manageable, it is not a daunting task. You can keep changing the API and updating the docs at the same time.
The docs can be useful to yorself as well. I always forget the details of the API that I have developed myself, and I constantly have to go and look them up to the reference.

**Comment by mmahalwy** [comment]
Salam all,

I will add docs to the api repo

**Comment by dashohoxha** [comment]
Any format, markdown, plain text etc. would be OK.

**Comment by mmahalwy** [comment]
@dashohoxha sounds good.
