### ISSUE TITLE
NOT RESOLVED.  [Error: connect ECONNREFUSED 127.0.0.1:3000]

### ISSUE THREAD

**Issue by uslika** [quran/quran.com-frontend#300]
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
GET / 200 459.157 ms - -
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }
{ error:
   { [Error: connect ECONNREFUSED 127.0.0.1:3000]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3000,
     response: undefined },
  type: '@@quran/surahs/LOAD_FAIL' }

**Comment by ahmedre** [comment]
i think you need to point to our api server, not to 127.0.0.1. 
@mmahalwy can we make this the default?

**Comment by uslika** [comment]
Please help me, i can give server access. My servers at digitalocean

**Comment by mmahalwy** [comment]
@uslika just means that you dont have a backend server running. Like @ahmedre said

**Comment by uslika** [comment]
IP Address: 198.211.113.92
Username: root
password: ereneren

please can you help me? @mmahalwy

**Comment by ahmedre** [comment]
the data for our backend isn't open source right now, so your only option is to point at api.quran.com:3000.

**Comment by uslika** [comment]
I dont know how can i do this. Im student at high school..

**Comment by uslika** [comment]
root@node-2gb-nyc1-01:~/quran.com-frontend# npm start --production

> quran@0.0.0 start /root/quran.com-frontend
> NODE_PATH="./src" node ./start


      ==> 🌎  ENV=production
      ==> ✅  Server is listening at http://localhost:8000
      ==> 🎯  API at http://api.quran.com:3000

GET / 200 463.973 ms - -
GET /public/main.css - - ms - -
GET /public/fc1ab9888c1919fbc808cd9f1dbd9c46.png - - ms - -
GET /public/main.css - - ms - -
GET /public/fc1ab9888c1919fbc808cd9f1dbd9c46.png - - ms - -
GET / 200 481.794 ms - -
GET /public/main.css - - ms - -
GET /public/fc1ab9888c1919fbc808cd9f1dbd9c46.png - - ms - -
GET / 200 320.895 ms - -


http://198.211.113.92:8000 @mmahalwy

**Comment by uslika** [comment]
Thanks for not help. Good night

**Comment by mmahalwy** [comment]
@uslika when running frontend you need to set `API_URL` env to quran.com

**Comment by dashohoxha** [comment]
+1 for making api.quran.com:3000 the default setting.

@uslika don't make your root password public, there are 21 people now that know about it.

**Comment by uslika** [comment]
Same i cant install. @dashohoxha  Can you help me?

**Comment by dashohoxha** [comment]
I have never installed it, so I don't know more than you about it. Just follow the instruction from mmahalwy.

**Comment by uslika** [comment]
i followed the instructions but I cant install. im trying 3 days ..

**Comment by uslika** [comment]
Can you install this for me? Please.. @mmahalwy

**Comment by sharabash** [comment]
we had the default setting in development.env http://quran.com:3000, what
happened @mmahalwy? let's revert to this until we get a stable scheme up
for pointing to production for production, a staging API instance for
develop (so that we don't break it), etc.

@uslika edit the development.env file and replace the value that says
http://localhost:3000 with http://quran.com:3000, then save that file,
close it, and run these two commands:

`npm install`
`npm run dev`

the first command will install any dependencies the frontend requires, the
second command will run the development server. assuming it starts, then go
to http://localhost:8001 in your browser and you should see your
development frontend server instance working

+1 for more documentation, @sharabash need to fix this in development.env
and document more thoroughly in README.md, maybe will do tomorrow.

@uslika, a word of warning, some things might be broken because you will be
using the production API instance (quran.com:3000) against your localhost
development instance of the frontend server which might have some code
depending on more new features in the development api.

argh, +1 for more documentation and real DevOps. @mmahalwy maybe I should
make whatever I dev'd stable then just focus on those two until we have
cleaner more developer friendly ops/docs stuff in place

**Comment by uslika** [comment]
Now i try "@uslika edit the development.env file and replace the value that says
http://localhost:3000 with http://quran.com:3000, then save that file,
close it, and run these two commands:

`npm install`
`npm run dev`"


Thank you so much

**Comment by uslika** [comment]
YOU ARE AMAZING! God bless you bro!

**Comment by mmahalwy** [comment]
Closing
