### ISSUE TITLE
redux-async-connect no longer maintained.

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#440]
Seems like `redux-async-connect` is no longer maintained. There is a fork project which has better React 15 support:

https://github.com/makeomatic/redux-connect

**Comment by mmahalwy** [comment]
@sabeurthabti i want to get rid of redux-async-connect and it's fork. This should be done in `onEnter` of router. Will get to this soon inshallah :)

**Comment by mmahalwy** [comment]
Or next year
'under promise and over deliver'

**Comment by sabeurthabti** [comment]
https://github.com/ryanflorence/async-props

**Comment by mmahalwy** [comment]
@sabeurthabti yeah, i saw these packages, and they are good, but they wrap the component rather than on the route level. Difference: you cannot do things like redirect on server side with status codes since it has to walk down the routes to generate and find if they have async requirements.

**Comment by atalebagha** [comment]
How about [Redial](https://github.com/markdalgleish/redial)?  it looks promising?

**Comment by atalebagha** [comment]
Sorry didn't notice @sabeurthabti's post

**Comment by mmahalwy** [comment]
@atalebagha i think we should use the `onEnter` hook for the router since, from my personal experience, I have been burnt with libraries like async-redux or redial that end up not getting maintained. React-router is all over the place too, so I can see a point for why not to go that route

**Comment by mmahalwy** [comment]
I want to bump this up and revisit this. I think we could have a snappier experience than the one we currently have.

The problem:
- Most users come to the homepage then navigate to the Surah they want.
- We have SSR because of SEO. And are most valuable when Google scraps our Surah pages
- That being said, when a user navigates from Home to Surah container, the page does nothing until all the data is loaded. This is by design that the same code is used for SSR and for client side routing due to `asyncConnect`. We should change that and have a faster/snappier experience for the user. We should get smart to wait to load the page for SSR but navigating to the page client side should show a loader or something.
