### ISSUE TITLE
Bug! while listening recitation, the audio stops suddenly. 

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#536]
Please see the screenshot for more details - 
http://prntscr.com/dlqlo4

**Comment by mmahalwy** [comment]
`412` status code is weird... anyone else seeing this problem?

**Comment by ahmedre** [comment]
this is the same issue we're seeing on audio.quran.com according to @sabeurthabti

**Comment by mmahalwy** [comment]
hmm weird :S

**Comment by murad073** [comment]
I think I could reproduce the problem. I faced it again while listening quran with repeater. Please see the screenshot - http://prntscr.com/dovn6g

**Comment by sabeurthabti** [comment]
Very weird, this only happens on Chrome.

**Comment by mmahalwy** [comment]
I think this should be fixed @ahmedre ?

**Comment by ahmedre** [comment]
yeah i fixed this al7amdulillah. the problem was that the ETags returned for the same file from different servers were different (due to differing "last modified times" on the files). synced the last modified times and it seems to be fixed now (though if you encounter it again with a file, try it again, since Chrome will try to re-play from cache, which might have the wrong ETag value).
