### ISSUE TITLE
Surah page needs to be refreshed for custom options to apply

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#550]
I am hitting a bug where my options (such as reciters, translations, reading mode, etc) get reset (when going to a surah from the quran.com homepage) and need to be refreshed. Sometimes a change in setting needs a refresh too in order to be applied.

Steps to reproduce:
- Go to quran.com
- Click on surah 1 (Al-Fatihah)
- Change the reciter, translations and/or reading mode from the default setting
- Note: Refreshing the page or going to quran.com/1 or a diffrent surah (e.g. quran.com/2) in a new tab will keep the correct settings
- Go to quran.com
- Click on surah 1 (Al-Fatihah)
- Note: the settings change back to default and require a refresh

Additional Info:
- Browser: Chrome 55.0.2883.103 (64-bit)
- Laptop: Toshiba Chromebook 2 (2014)
- OS: Chrome OS

If this is a legitimate bug I can try to tackle it when I get a chance.

**Comment by SanPilot** [comment]
I've dug around a little - I don't know the cause but can help.

The settings are stored in a cookie named 'options'. When I change the Reciter, for example, the cookie, which is URL encoded JSON, changes to my new setting (in this case, the "audio" property changes).

Strangely, when I go from quran.com/1 to the homepage and back to quran.com/1, the cookie remains but the setting is not applied. The issue seems to be that the page is ignoring the cookie.

This behavior is particularly curious since, like OP said, navigating to a different Surah does not cause the issue.

**Comment by mmahalwy** [comment]
@umairidris @SanPilot thanks for looking into this issue. Might be great to centralize the options into one place and add this feature request: https://github.com/quran/quran.com-frontend/issues/552
