### ISSUE TITLE
Translate the site into Indonesian

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#588]
Indonesia is one of our most visited countries. Let's add translation to it?

**Comment by gozali** [comment]
+1

PS: I'm Indonesian

**Comment by ahmedre** [comment]
we have support for Indonesian in Quran for Android.
one of the very important things we need to figure out is how to sync translations between Quran.com, Quran for Android, and Quran for iOS. this is especially since we do get corrections of typos (or things that were fixed in later revisions by the author) that we update, and we don't want to update on all 3 platforms independently.

**Comment by ahmedre** [comment]
@habibr since you helped with the localization for Android, do you want to do the Indonesian localization for quran.com?

**Comment by habibr** [comment]
Quran.com is also my favorite quran site. I'd like to help too...

**Comment by mmahalwy** [comment]
@gozali would you like to push a PR translating the `en.js` file into Indonesian?

**Comment by mmahalwy** [comment]
CC @habibr

**Comment by redhae** [comment]
are we supporting Malay/Bahasa Melayu. i can help with that, insha'Allah

**Comment by mmahalwy** [comment]
@redhae please do! Looking forward to a PR!

**Comment by habibr** [comment]
So, how do i start?

**Comment by ahmedre** [comment]
@habibr add a file for Indonesian here:
https://github.com/quran/quran.com-frontend/tree/master/src/locale

i think it should be `id.js` - use the English one as a starting point and then give a PR - jazakAllah khairan.

**Comment by imiro** [comment]
+1 I'm Indonesian too, happy to help!
