### ISSUE TITLE
Add search input in top nav

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#593]
@umairidris would love to get your thoughts on this too. @ahmedre suggest we bring it back. I'd image it to look like:

![image](https://cloud.githubusercontent.com/assets/3749095/22098379/d2dc61e4-ddda-11e6-9593-8765780b10ac.png)

**Comment by umairidris** [comment]
Looks good to me. I am guessing in mobile view it will contract to a single search icon?

Ideas for how to expand this in future:
- When you are in a surah it will search by default in the surah otherwise the whole quran (should be clear in the text hint inside the search bar)
- There can be a [dropdown](https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Ic_arrow_drop_down_48px.svg/2000px-Ic_arrow_drop_down_48px.svg.png) on the right edge which users can press to bring up a popup where they can select to search specific surahs (or all)
