### ISSUE TITLE
Bug on Chrome

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran.com-frontend#617]
saw this today on Chrome while browsing quran.com.

<img width="1029" alt="screen shot 2017-01-23 at 11 48 13 am" src="https://cloud.githubusercontent.com/assets/2100167/22221782/3fea9602-e169-11e6-8515-43b671f4602e.png">
<img width="1118" alt="screen shot 2017-01-23 at 11 48 33 am" src="https://cloud.githubusercontent.com/assets/2100167/22221783/3feca924-e169-11e6-8a35-5f6cb39415e7.png">

**Comment by ahmedre** [comment]
btw, let me clarify - these are 2 separate screenshots.
the first one is missing a word (wa astakbaru). teh second one has the word "alsalihat" in the wrong place. note that this is very very similar to the Chrome for Android issue i mentioned in #548).

also, this is on Chrome for OSX, with no crazy extensions or anything, and it's probably the stable version (i can find out if needed).

**Comment by mmahalwy** [comment]
@ahmedre rarely am I scratching my head trying to wrap my head around what is going on... and this is one of those cases. We are pretty broken on Chrome (whether OSX or Android) and I have no idea why. I have a feeling it's Chrome specific but have no clue. And it's definitely not a recent change that caused this since this was noted on production before the 111 commits deployed last week. :( 

I don't know what to do :S

**Comment by ahmedre** [comment]
cc @sabeurthabti and @naveed-ahmad as maybe they have some ideas?

**Comment by sabeurthabti** [comment]
Can you share a link? I cant replicate it on latest chrome: https://quran.com/7/43 . There was a chrome release recently.

**Comment by ATouhou** [comment]
still broken on Android, Google Chrome v. 55.0.2883.91
