### ISSUE TITLE
Show Juz/Siparah, Minzal, Hizb for each verse  

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#652]
I believe we had this in past, or someone tried to implement this.

**Comment by sabeurthabti** [comment]
I think we had one also raised for page mode.

**Comment by murtuzasyed** [comment]
Is this issue open?

**Comment by naveed-ahmad** [comment]
@murtuzasyed yes.

**Comment by mmahalwy** [comment]
@atiqueansari1987 any luck?

**Comment by atiqueansari1987** [comment]
@mmahalwy Didn't get chance to work on this yet.

**Comment by Dhul-Husni** [comment]
asalamu aleikum @atiqueansari1987  i've got a bit of time in my hands this week InshaAllah can I take this up

**Comment by Dhul-Husni** [comment]
Asalamu aleikum @sabeurthabti i am working on this inshaAllah and i have seen that you had also tried something similar. MashaAllah part of this has been implemented but It's hard to implement for new pages which are start of juz or hizb because the state changes and one cannot compare the juzNumber with the previous verse juzNumber. I was thinking of making a dictionary with all juz and hizb start numbers and check if a verse is in the dictionery. If it is show the hizb and juz tag.
sorry for dictionery i meant object
@sabeurthabti  @naveed-ahmad  @mmahalwy inshaAllah what are your thoughts on this.
