### ISSUE TITLE
Audio skipping bug

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#67]
Audio skipping bug (due to memory). When the user changes the played ayah in the middle the ayah is skipped to the point it was at before. Example: the user starts playing Surah Fatihah, in the middle of the second ayah the user clicks ayah one. Then when the audio starts ayah two it goes directly to the middle of the ayah, and continues playing.

**Comment by ahmedre** [comment]
This will improve automatically when we switch to gapless recitations since
it's one file per sura.

**Comment by sharabash** [comment]
how do you propose switching to gapless recitations? do we have timings? do we have an issue for switching to gapless recitations? if not, let's create one

**Comment by ahmedre** [comment]
instead of loading 001001.mp3 for ayah 1, 001002.mp3 for ayah 2 and so on, we instead load 001.mp3 which is the full sura. we have a timing file (on Android, this lives in a sqlite database, so for us, it can live in our backend database) that says where each ayah starts and ends.

if you play sequentially, you just check every second to see what bounds of which ayah you are in. if you want to jump to a particular ayah, you just seek to the timing in the file, and so on.
