### ISSUE TITLE
Page not loading fully

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#745]
Salaam. I navigated to https://quran.com/38/75 this morning and received the following. 
Nothing else loads on the page:

![image](https://cloud.githubusercontent.com/assets/791996/25182394/506329ba-24c9-11e7-8e0b-bd23124ae0f5.png)

**Comment by ysofi** [comment]
Wa-alaikum salam, is it still doing that?

![chrome_38_75](https://cloud.githubusercontent.com/assets/17520348/25187454/a4b4b74a-2555-11e7-8339-8ee0cc95a7f6.gif)

Just tried on Chrome 57 and it seems fine from here (although it may be loading from a different server due to region). Wasn't cookies as it was a new incognito window.

**Comment by ysofi** [comment]
Somebody (ticket #7838) recently mentioned the same behaviour for quran.com/33/73 and it checks out.

Tried on multiple browsers and it's reproducing.

**Comment by AskYous** [comment]
It's working now! I'll close this issue.

**Comment by ysofi** [comment]
Alhamdulillah.
