### ISSUE TITLE
The play() request was interrupted by a call to pause() 

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#786]
Chrome is throwing lot of these warning/errors, and sometime playback also stop.

**Comment by iMoe037** [comment]
This error usually happens when going from one ayah to the next. Two states are being maintained one isPlaying in the Redux store, and another state within the store. It's one of the properties (it starts or contains the word media).  Judging by this stackoverflow[https://stackoverflow.com/questions/36803176/how-to-prevent-the-play-request-was-interrupted-by-a-call-to-pause-error](url). On the pause redux action we need to check if the media object is playing before we call the pause function.

**Comment by naveed-ahmad** [comment]
@iMoe037 JAK for debugging, feel free to take this task.

**Comment by mannanali413** [comment]
@naveed-ahmad @iMoe037 i guess this task is open. I can take this up

**Comment by iMoe037** [comment]
@mannanali413 go for it.

**Comment by bahaa96** [comment]
Is this still open ??
