### ISSUE TITLE
Arabic Search broken Fonts

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#796]
<img width="1199" alt="screen shot 2017-05-22 at 11 14 56 pm" src="https://cloud.githubusercontent.com/assets/47771/26340672/88e93e88-3f44-11e7-8af5-a7137ac834a6.png">

100% repro on Chrome - search for:
رحمة

also note that the experience when searching for Arabic isn't great - sometimes the autosuggestion box won't close, for example.

**Comment by ahmedhazemfekry** [comment]
nice work guys, I need to know which font you use and if there is a specific script for Quraan you use
thanks in advance

**Comment by imadmk** [comment]
![image](https://user-images.githubusercontent.com/6089932/29643364-e23a377e-8898-11e7-96f0-79f226d11605.png)
I got this on my chrome. I don't know maybe because chrome native font?

And the autosuggestion box i found won't close for any language when we do search in the `/search` page or after we do search on homepage

Is somebody already working on this?

**Comment by mmahalwy** [comment]
No one is working on this currently. Although the problem of tafsir showing up in search results has surfaced many many times :(

**Comment by naveed-ahmad** [comment]
We need setting for search where users can choose the language they want to search or disable all languages. But divehi font is fixed now.
