### ISSUE TITLE
Some of the translations are not correct in some verses of the quran, need to mark the translation as "not approved" till it been reviewed and approved by language specialist 

### ISSUE THREAD

**Issue by HaiderMaklef** [quran/quran.com-frontend#931]
**I'm submitting a ...**
- [ X] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
some of the translations are not correct, if you copy the same verse into google translation for example you will find that translation give is false and google show more accurate translation, it seems some of these translations represented the view of a specific school of thought and not the majority of what the Muslim  community agreed about, we should not let our own thought corrupted the true meaning of Quran..

**Expected / new behavior:**
Separate the translation from the text by providing only the text of quran or make the translation optional for those who want to see it 

**For issue, please provide steps to reproduce it:**
Check the translation of the current verse :  وامسحوا برؤوسكم وأرجلكم 
Google transliteration : "wipe your head and your feet" ---which is correct 
Quran.come translation : "wipe over your heads and wash your feet" -- which is incorrect,  this translation add the part of "and wash" where it should be only "and", the word "wash" is extra and given a false meaning ..

**Anything else:**
thank your for your great work ...

**Comment by sabeurthabti** [comment]
@HaiderMaklef thank you for raising this issue. As you know this project is open source and we are always looking for contributors. Any way I can help you make these contributions?

translations can be found here: https://github.com/quran/quran.com-frontend/tree/master/src/locale

**Comment by ahmedre** [comment]
> we should not let our own thought corrupted the true meaning of Quran..

absolutely - which is why none of the translations on quran.com are our own - none are translated by our team. Quran.com currently has 11 english translations, each of which were published by their authors after having been reviewed by scholars and so on.

Quran translations are not intended to be word by word translations - they're translations of the meanings of the Quran. please review the other 10 translations and you'll see that the meaning is consistent between all of them, and the differences are subtle between them. differences are to be expected because Quran translations are, in fact, "interpretations of the meanings of the Quran," which may differ between the scholars, but the point is that all are within the bounds of acceptable interpretations in accordance to the Quran and sunnah.

please take the verse and the 11 translations to a sheikh and ask him to explain this to you in detail insha'Allah.

**Comment by HaiderMaklef** [comment]
Dear ahmedre 

For the first part of your answer, would you please reference these 11 English translations so we can submit a fix for all them, because for sure the all wrong. anyone with some simple Arabic reading skills will tell you the word “WASH” is not part of the original text for that phrase of the Quran.

Those who understand it as “WASH” not “WIPE” are doing that on their own responsibility but for sure this is not the actual text of the Quran. In order to prove it to you, listen to any famous Quran reciters, they will never include the word “WASH” in the middle of that phrase. It is always the false interpretation do that not the Quran itself.  Millions of Muslims today WIPE not WASHING in their everyday “Wadu’u”.

Once again, it seems some of these translations represented the view of a specific school of thought and not the majority of what the Muslim community agreed about, we should not let our own thought corrupted the true meaning of Quran..

You mention this ** Quran translations are not intended to be word by word translations**, this a false statement. IT IS ALWAYS THE BEST PRACTICES FOR TRANSLATION TO MATCH THE EXACT WORDS OF THE ORIGINAL TEXT, the only time we not translate “word by word” when there is NO equivalent replacement for that in the other language. And that is not apply here because the phrase use very simple words can be translated easily into any language without need to add extra words. In fact, in this case it really bad because it CHANGED THE MEANING OF THE TEXT into a complete different output.
I believe your false statement come out of the misunderstanding the difference between “translation of Quran” and “translation of the TAFSEER of the Quran”, what you call a “Translation of the Quran” it’s NOT, this is a “Tafseer” of the Quran. 

Tafseer is the way how each group in Islam interpret the meaning of the Quran depending on what the basis of them own school of thought, which mean that the Tafseer is represents people opinion which can be vary depending on many factors. Once again “we should not let our own thought corrupted the true meaning of Quran”.

here are a few general rules of thumb about best practices for interpretation:
-	Interpreter refrains from interjecting personal opinions.
-	Interpreter does not change the register (the level of speech) whether very technical or erudite, or a child’s speech.
https://www.wccusd.net/cms/lib/CA01001466/Centricity/Domain/76/07_Best_Practices_for_Translation_and_Interpretation.pdf

I already ask every single Shaikh about that and for sure there is no word “WASH” in that phrase, you can tell yourself by listing for any Quran reciter out there, they will never but “WASH” in the middle…

Thank You.

**Comment by ahmedre** [comment]
minor clarifications

1. the entire team is very careful to make sure we only put sunni content and to avoid any non-sunni content, since this is our responsibility. the English translators here are known to be from the ahl al sunnah wal jama3a - if any aren't that somehow we missed, we'll be happy to remove whichever ones aren't.
2. we provide the translations as is - we do not type them, nor do we translate them, nor do we change them aside from fixing typos as mentioned before - we are providing it - "this is the translation of {translator}."

as to your question - i cannot debate with you on any of this because i am not a scholar and don't have enough knowledge to - we are providing the translations, so i recommend you reach out to the translators and ask them why they did this (and their boards and ask them why they approved it).

on our end, we will consult one of the shuyookh and ask them to read this issue and tell us what they suggest we do in this case.

**Comment by HaiderMaklef** [comment]
***we only put sunni content**** did the "Sunni content" mean people are free to change the text of the Quran whenever they want ?!!!!
if you want to put your own thought or specific school thinking into that, you should never call it "Quran translation". give it another name, say "this my group opinion" or in this case "Sunni way of thinking", why you mislead the people into a false transaction ?!!!

**Comment by ahmedre** [comment]
maybe i am not explaining myself well to you akhi - let me put it another way. if you go to an Islamic bookstore and buy one or more of the translations we have and compare them to what we have on our site. you shall find that they are identical.

who am i or who are any of us to try to change the word of Allah? we fear Allah's punishment if we tried to do something like this.

**Comment by HaiderMaklef** [comment]
Dear Ahmed, 
you don't need to go to any bookstore any more, the internet have everything :) every single translation i fond online is not including "WASH",  here is an example online : 
http://quran.al-islam.org/
From the options window at the left upper, I checked "Arabic" then i checked the first English translation "Shakir (English)", then i select "5. al-Maaida (The Table)" and then under that "Aayaat (Verses): From 1 to 120" -the default- , and clicked "Display":
 To the right of the screen please scroll down to the translation of Aayaa 5:
[Shakir 5:6] O you who believe! when you rise up to prayer, wash your faces and your hands as far as the elbows, and wipe your heads and your feet to the ankles; **wipe your heads and your feet** ...NO "WASH"..
Thank You

**Comment by ahmedre** [comment]
our Shakir translation matches that website's - as does our Yusuf Ali and Pickthal - please verify for yourself. The Shakir one indeed doesn't use wash (both websites), but Yusuf Ali and Pickthal do (both sites).

<img width="768" alt="screen shot 2018-01-24 at 11 12 02 am" src="https://user-images.githubusercontent.com/47771/35319018-741ede48-00f7-11e8-86c5-4ab998d9f806.png">

closing this issue since this is consistent with what the translator has in their book. if the translator changes it in a newer revision, happy to update to the newer revision insha'Allah in the future.

**Comment by HaiderMaklef** [comment]
how to access these translations from the user UI ?

**Comment by ahmedre** [comment]
tap settings in the top right corner of the screen.
tap translations.
choose the boxes of the translations you want visible.

**Comment by HaiderMaklef** [comment]
Thank You very much for you hep, i did not see the other translations, maybe it better if we have a drop-down in the top of each section to allow the user to change the translation without go deep into the settings configurations ...
Please close this one...

**Comment by hammady** [comment]
Just to reiterate, the approved translations are those of Sunni. Some pointers that could clarify the confusion:
1. al-islam mentioned above it Shiite.
2. Shiite belief is to wipe not to wash.
3. The name "Haider" itself looks like Shiite to me.
If we stick the label "Sunni" to the translations, that would prevent such endless debates.
