### ISSUE TITLE
Ramadan 2018 goals, tasks, features

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#946]
Salam all,

Wanted to create this issue as a discussion for Ramadan 2018 goals, tasks, features and bugs. Anyone in the community is welcomed to add comments and/or suggestions. Feel free to comment suggestions and I could add them to a list in this comment (I will edit it continuously).

cc @ahmedre @sharabash @hammady @naveed-ahmad @sabeurthabti

**Comment by Muhammadibn** [comment]
The search feature needs to be worked on. The one on the legacy site works so much better. Before typing this comment again, I just tried it out and typed qulillahumma in both version. The new version didn't give any results where as the legacy site gave the exact ayah I was looking for.

**Comment by sabeurthabti** [comment]
- We can work on improving the homepage - I think we wanted a better design anyway. 
- Bring quran.audio to the same standards as quran.com (maybe even share audio players_
- I'd love to do some out reach at events here in the UK and get people excited and contributing to quran.com (not just code)
- Maybe quran.audio Android app (I know I dropped the ball on that one)

**Comment by nase7ah** [comment]
Salam 'alaykum and jazakum Allah Khayran for all of your efforts!

I have a small set of easy proposals that don't require much work that I think may benefit the project, specifically the security of the websites.

Since there's a push everywhere to move to HTTPS I think the first task should be to:

1. Moving everything to HTTPS:

There are still some domains that don't even support HTTPS (legacy.quran.com, salah.com, ...) Fortunately Let's Encrypt is free and easy to setup (with automation tools like certbot.eff.org).

Once done one can add them to the HSTS preload list to make sure that they're always loaded over HTTPS (they can be included there even if they don't meet the full criteria, I think but I may be wrong, of the HSTS preload list hstspreload.org by contacting its maintainers).

2. Ameliorating security headers

For example adding a CSP and set the Secure flag for cookies, as well as adding Subresource Integrity for scripts that are loaded https://observatory.mozilla.org/analyze/quran.com

3. Moving to jsDeliver whenever possible

One of the reasons (besides the speed, the number of CDNs that they use, ...etc) is that they are guaranteed to not be blocked in China.

**Comment by mxahmed** [comment]
Hello everyone, I've only known about quran.com today as I was thinking about implementing something similar but seems like it's a better idea to help this project than to start a new one.

Unfortunately I'm mainly a python developer with some intermediate experience in the frontend land [ angular & angularjs ] so It wouldn't be easy for me to contribute in the frontend or backend parts, but I'll surly follow the issues and see if I can help with anything or to see if I can help with any of the python based parts of the project.

As for suggestion of new features or improvements,
One thing that will be very good to have is Tafser of each Aya in the reading page.

Thank you all for the amazing effort and hope to be of any help to this amazing project.

**Comment by Dhul-Husni** [comment]
@mxahmed  React is not as hard. I promise. I am also a python dev but i was able to learn react in a few weeks and start contributing. InshaAllah may Allah make it easy for you. I also want to embark on a python project here at quran.com for teaching people how to learn classical Arabic with AI not theafter ramadhan inshaAllah and it will be in python maybe we could work together then inshaAllah.

**Comment by mustafa0x** [comment]
I don't think the search needs smartening — it needs dumbing down. Take the term that quran.com suggests: "Noah". The 2nd result doesn't even have Noah in the ayah — it's just mentioned in between brackets by some of the translators.

**Comment by abdulbasitkay** [comment]
Assalamu Alaikum
We could add to the goals moving of statics artefacts of quran.audio to CDN and maybe issue quran/audio.quran.com#105?

**Comment by mmahalwy** [comment]
@mustafa0x i agree. we need to fix search again. it used to be much much better. it's just a big pain to tweak :(
